### ISSUE TITLE
[Discussion] Is `osu_scores_high` `UNLOGGED`?

### ISSUE THREAD

**Issue by ThatOneCalculator** [ppy/osu-infrastructure#1]
Having a table be `UNLOGGED` can lead to [much faster performance](https://www.depesz.com/2011/01/03/waiting-for-9-1-unlogged-tables/) (if you're using postgresql). Maybe give it a try if it's not already unlogged?

```sql
ALTER TABLE "osu_scores_high" SET UNLOGGED
```

**Comment by peppy** [comment]
We are not using postgresql.
