### ISSUE TITLE
Replay handling for imported (and new) `solo_scores`

### ISSUE THREAD

**Issue by peppy** [ppy/osu-infrastructure#11]
Just documenting some IRL discussion regarding the path forward with migration of the `has_replay` flag (aka knowing if a score has a replay available), which is currently not present in the new `solo_scores` schema.

This was decided with the goal of keeping things simple and flexible for now, and may change in the future once we have the systems online.

Current proposal:
- Add `BOOL has_replay` to `solo_scores`
- Add `legacy_score_id` to JSON `data` (alternative is to add a second index to `legacy_id_map` table, but feels like the legacy ID should be in the json data)
- Change replay retrieval code to first retrieve using `solo_score.ID` and falling back to `solo_score.data.legacy_score_id`.
- Migrating S3 data from legacy to new IDs once everything has settled (then removing the fallback).

Tasks to make this happen:
- [x] Run online schema changes to add new `has_replay` column
- [x] Update `ImportHighScores` (ppy/osu-score-statistics-processor) to include `legacy_score_id` and `has_replay`
- [x] Update web-10 submission to correctly update the new flags (on replay deletion)
- [x] Update web-10 and osu-web replay retrieval to perform fallback lookups 
- [ ] Migrate existing replays to new IDs on S3

cc/ @nanaya @smoogipoo

**Comment by bdach** [comment]
> Update web-10 and osu-web replay retrieval to perform fallback lookups

I dunno about web-10 but from the work I've done on replays I _believe_ osu-web should be doing fallbacks for legacy replays already:

https://github.com/ppy/osu-web/blob/e3424e755c5c411c3ba1b1d90c26fe6db62c1f85/app/Http/Controllers/ScoresController.php#L37
https://github.com/ppy/osu-web/blob/e3424e755c5c411c3ba1b1d90c26fe6db62c1f85/app/Http/Controllers/ScoresController.php#L50-L52

**Comment by peppy** [comment]
web-10 will still need changes after we eventually deploy (stable directly requests replays from a web-10 endpoint), but I won't be applying these until later in the process.

**Comment by peppy** [comment]
This is completed. Of note, we're not migrating replays across to the new storage for now as they are in a different format and it would be a large task. Can be revisited at a later point in time.
