### ISSUE TITLE
[Discussion] OpenSearch instead of ElastiSearch

### ISSUE THREAD

**Issue by ThatOneCalculator** [ppy/osu-infrastructure#2]
> Create a new elasticsearch schema

[OpenSearch](https://github.com/opensearch-project/OpenSearch) is a fork of ElastiSearch that's more performant. Maybe give it a shot?

**Comment by peppy** [comment]
We already have things working fine using elasticsearch and have not even come close to hitting any performance bottlenecks. I believe in not making changes until they are required.
