### ISSUE TITLE
Populate `max_combo` in `osu_beatmaps` using `osu-difficulty-calculator`

### ISSUE THREAD

**Issue by peppy** [ppy/osu-infrastructure#22]
See https://github.com/ppy/osu-web/issues/10566

Ensure that only `max_combo` is written to avoid applying new diffcalc version.

**Comment by smoogipoo** [comment]
As I'm also now realising the changes in https://github.com/ppy/osu-difficulty-calculator/pull/224 aren't going to be enough... Basically it looks like we're going to need 3 queues? One for each of difficulty, max_combo and scoring attributes?

**Comment by peppy** [comment]
I'd sooner backport an old osu.Game package than have three going. Or find another way. So hold off this for now until I get a chance to assess the situation.

**Comment by peppy** [comment]
I've begun reprocessing graveyarded beatmaps and populating `max_combo`. This should be done in under a day.

WIth regards to 

> Basically it looks like we're going to need 3 redis queues? One for each of difficulty, max_combo and scoring attributes?

For now this isn't high priority. osu-web will fallback to using the difficulty attributes table if `max_combo` is zero in `osu_beatmaps`. We can backfill in the future. If we want to have things populating, we can update the last `release-diffcalc` to populate the field (should be pretty low-risk to push a new build from the known stable branch).

As for scoring attributes, what are the main uses of these currently?

**Comment by bdach** [comment]
> As for scoring attributes, what are the main uses of these currently?

That'd be the `osu-queue-score-statistics` legacy score importer, wouldn't it? After https://github.com/ppy/osu-queue-score-statistics/pull/155 it will read the scoring attributes for the purpose of converting imported stable high scores to standardised scoring.

**Comment by peppy** [comment]
Right, so it's part of the deploy-everything chain. WIll revisit that in line with those changes (maybe needs to be added to a deploy todo list, can you grab that @bdach ?).

**Comment by bdach** [comment]
I think the deploy list reflects everything I mention above already actually, so there's nothing to update.

**Comment by peppy** [comment]
Population has complete. I've also updated the legacy API to read from the new column before falling back to `difficulty_attribs`.

From this angle, we should be fine without any further changes from a `max_combo` perspective – all new beatmaps hitting BSS will still write entries to the attribs table, so as long as we don't do another purge users will not notice any difference.

Before the next graveyard purge we should revisit the situations here.
