### ISSUE TITLE
Investigate adding a new column for rankability of individual scores

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-infrastructure#26]
While we can control the rankability (i.e. for pp) of individual builds via the `osu_builds` flag, it may be worthwhile to also be able to control the rankability of individual _scores_.

For example, if we want to unrank only those scores set for a particular mod.

**Comment by peppy** [comment]
I've added this:

```sql
alter table scores add ranked tinyint(1) default 1 not null after preserve;
```

There are some other schema changes as well (mostly related to partitioning) so we should sync with osu-web schema at some point.
