### ISSUE TITLE
Osu! Lazer Scores not showing on profile

### ISSUE THREAD

**Issue by Devehh** [ppy/osu-infrastructure#29]
I have set multiple plays in Osu! Lazer that do not show on my public profile, let me provide examples;

![image](https://github.com/ppy/osu-infrastructure/assets/87140321/d1b9e854-0a0f-4d53-a31b-f39db0c24da2)
Here, you can see a play I set on "how to create the weeknd's "blinding lights"" by Seth Everman. Here you can see that this submitted score added 162pp play to my profile.
![profile](https://github.com/ppy/osu-infrastructure/assets/87140321/f0162226-5084-40af-801f-e3b0567ae9cc)
This is a screenshot of my profile as you can see, the play does not show up. I will provide one more example:
![image](https://github.com/ppy/osu-infrastructure/assets/87140321/dbad6a40-576d-45f9-a4c0-171d66936d2a)
As you can see in this image I set a 202pp play on "Horrible Kids" by Set It Off. If you look at the previous screenshot of my profile you can see I have Lazer mode selected and these plays do not show up on my public profile. Is this a visual bug, or a bug with submitting scores, I would really like to have this issue resolved as it is my first 200pp play and another score with a decent pp count. Thank you for reading. (Both of these scores were set over a week ago btw)

**Comment by bdach** [comment]
Classic mod does not give pp in lazer right now. So technically this is not a bug.
